from . import finsetter_messaging
from . import finsetter_policy_product_line
from . import finsetter_testimonial
from . import finsetter_financial_product
from . import finsetter_lead_product_match
from . import finsetter_policy
from . import finsetter_claim
from . import finsetter_call_log
from . import finsetter_consent
from . import finsetter_campaign
from . import finsetter_appointment
from . import finsetter_document
from . import crm_lead
from . import crm_team
from . import res_partner
from . import res_config_settings
